name: Update card list
on:
  schedule:
    - cron: 1 19 * * *
    - cron: 1 20 * * *
  workflow_dispatch: {}
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: node update-cards.mjs
      - run: node creator-decks.mjs
      - run: |
          git config user.name card-bot
          git config user.email actions@users.noreply.github.com
          git add cards.json card-changes.json variants.json creator-decks.json creator-stats.json
          git diff --cached --quiet || (git commit -m update-data && git push)
